import { auth, db, signInWithEmailAndPassword, createUserWithEmailAndPassword, onAuthStateChanged, signOut, collection, addDoc, getDocs, doc, updateDoc, deleteDoc, query, orderBy, serverTimestamp } from './firebase.js';

const state={produtos:[],clientes:[],fornecedores:[],compras:[],vendas:[],carrinho:[],pagamento:'Dinheiro'};
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const dateBR=new Intl.DateTimeFormat('pt-BR');
const $=id=>document.getElementById(id); const hoje=()=>new Date().toISOString().slice(0,10); const mes=()=>new Date().toISOString().slice(0,7); const fmt=v=>money.format(Number(v||0));
let chartDias, chartPag, chartResumo;
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
async function col(name,ord){const q=ord?query(collection(db,name),orderBy(ord,'desc')):collection(db,name);const s=await getDocs(q);return s.docs.map(d=>({id:d.id,...d.data()}))}
async function refresh(){state.produtos=await col('produtos','criadoEm'); state.clientes=await col('clientes','criadoEm'); state.fornecedores=await col('fornecedores','criadoEm'); state.compras=await col('compras','data'); state.vendas=await col('vendas','criadoEm'); renderAll()}
function renderAll(){renderProdutos();renderProdutosVenda();renderClientes();renderFornecedores();renderCompras();popularSelects();dashboard();relatorio();}

// auth
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('senha').value);toast('Login realizado')}catch(err){toast('Erro no login. Confira e-mail e senha.');console.error(err)}});
$('criarUsuario').addEventListener('click',async()=>{try{await createUserWithEmailAndPassword(auth,$('email').value.trim(),$('senha').value);toast('Usuário criado')}catch(err){toast('Erro ao criar usuário. Ative Authentication no Firebase.');console.error(err)}});
$('sair').addEventListener('click',()=>signOut(auth));
onAuthStateChanged(auth,async user=>{if(user){$('login').classList.add('hidden');$('app').classList.remove('hidden');await refresh()}else{$('app').classList.add('hidden');$('login').classList.remove('hidden')}});

// nav
const titles={dashboard:['Dashboard','Resumo geral da Canecas del Rei'],venda:['Nova venda','Venda rápida com baixa automática no estoque'],produtos:['Produtos','Cadastro e controle de estoque'],clientes:['Clientes','Cadastro de clientes'],fornecedores:['Fornecedores','Cadastro de fornecedores'],compras:['Compras','Entrada de estoque e saída financeira'],relatorios:['Relatórios','Fechamento por período e exportação CSV']};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');$('titulo').textContent=titles[b.dataset.page][0];$('subtitulo').textContent=titles[b.dataset.page][1]});
$('dataHoje').textContent=dateBR.format(new Date()); $('compraData').value=hoje(); $('relInicio').value=mes()+'-01'; $('relFim').value=hoje();

// produtos
$('produtoForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('produtoId').value;const p={nome:$('produtoNome').value.trim(),sku:$('produtoSku').value.trim(),categoria:$('produtoCategoria').value.trim(),preco:+$('produtoPreco').value||0,custo:+$('produtoCusto').value||0,estoque:+$('produtoEstoque').value||0,minimo:+$('produtoMinimo').value||0,imagem:$('produtoImagem').value.trim(),ativo:$('produtoAtivo').value==='true',atualizadoEm:new Date().toISOString()}; if(!p.nome||p.preco<=0)return toast('Informe nome e preço.'); if(id) await updateDoc(doc(db,'produtos',id),p); else await addDoc(collection(db,'produtos'),{...p,criadoEm:new Date().toISOString(),timestamp:serverTimestamp()}); e.target.reset();$('produtoId').value='';$('produtoAtivo').value='true';toast('Produto salvo');refresh()});
$('cancelarProduto').onclick=()=>{$('produtoForm').reset();$('produtoId').value=''}; $('buscaProduto').oninput=renderProdutos; $('buscaVenda').oninput=renderProdutosVenda;
function renderProdutos(){const busca=($('buscaProduto').value||'').toLowerCase();const lista=state.produtos.filter(p=>[p.nome,p.sku,p.categoria].join(' ').toLowerCase().includes(busca));$('tabelaProdutos').innerHTML=lista.length?lista.map(p=>`<tr><td><b>${p.nome}</b><br><small>${p.sku||'Sem SKU'}</small></td><td>${p.categoria||'-'}</td><td>${fmt(p.preco)}</td><td>${fmt(p.custo)}</td><td><span class="badge ${(+p.estoque<=+p.minimo)?'gold':'green'}">${p.estoque||0}</span></td><td>${p.ativo?'<span class="badge green">Ativo</span>':'<span class="badge red">Inativo</span>'}</td><td><button class="btn light" onclick="editProduto('${p.id}')">Editar</button> <button class="btn danger" onclick="delProduto('${p.id}')">Excluir</button></td></tr>`).join(''):'<tr><td colspan="7">Nenhum produto.</td></tr>'}
window.editProduto=id=>{const p=state.produtos.find(x=>x.id===id); if(!p)return; $('produtoId').value=p.id;$('produtoNome').value=p.nome||'';$('produtoSku').value=p.sku||'';$('produtoCategoria').value=p.categoria||'';$('produtoPreco').value=p.preco||'';$('produtoCusto').value=p.custo||'';$('produtoEstoque').value=p.estoque||0;$('produtoMinimo').value=p.minimo||0;$('produtoImagem').value=p.imagem||'';$('produtoAtivo').value=String(p.ativo!==false);document.querySelector('[data-page="produtos"]').click()};
window.delProduto=async id=>{if(confirm('Excluir produto?')){await deleteDoc(doc(db,'produtos',id));toast('Produto excluído');refresh()}};

// clientes e fornecedores
$('clienteForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('clienteId').value;const c={nome:$('clienteNome').value.trim(),whatsapp:$('clienteWhatsapp').value.trim(),email:$('clienteEmail').value.trim(),obs:$('clienteObs').value.trim(),atualizadoEm:new Date().toISOString()}; if(!c.nome)return toast('Informe o nome.'); if(id) await updateDoc(doc(db,'clientes',id),c); else await addDoc(collection(db,'clientes'),{...c,criadoEm:new Date().toISOString(),timestamp:serverTimestamp()}); e.target.reset();$('clienteId').value='';toast('Cliente salvo');refresh()});
$('fornecedorForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('fornecedorId').value;const f={nome:$('fornecedorNome').value.trim(),contato:$('fornecedorContato').value.trim(),categoria:$('fornecedorCategoria').value.trim(),obs:$('fornecedorObs').value.trim(),atualizadoEm:new Date().toISOString()}; if(!f.nome)return toast('Informe o fornecedor.'); if(id) await updateDoc(doc(db,'fornecedores',id),f); else await addDoc(collection(db,'fornecedores'),{...f,criadoEm:new Date().toISOString(),timestamp:serverTimestamp()}); e.target.reset();$('fornecedorId').value='';toast('Fornecedor salvo');refresh()});
$('cancelarCliente').onclick=()=>{$('clienteForm').reset();$('clienteId').value=''}; $('cancelarFornecedor').onclick=()=>{$('fornecedorForm').reset();$('fornecedorId').value=''};
function renderClientes(){$('listaClientes').innerHTML=state.clientes.length?state.clientes.map(c=>`<div class="info"><div><strong>${c.nome}</strong><small>WhatsApp: ${c.whatsapp||'-'}</small><small>E-mail: ${c.email||'-'}</small><small>${c.obs||''}</small></div><div><button class="btn light" onclick="editCliente('${c.id}')">Editar</button> <button class="btn danger" onclick="delCliente('${c.id}')">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhum cliente.</div>'}
function renderFornecedores(){$('listaFornecedores').innerHTML=state.fornecedores.length?state.fornecedores.map(f=>`<div class="info"><div><strong>${f.nome}</strong><small>Contato: ${f.contato||'-'}</small><small>Categoria: ${f.categoria||'-'}</small><small>${f.obs||''}</small></div><div><button class="btn light" onclick="editFornecedor('${f.id}')">Editar</button> <button class="btn danger" onclick="delFornecedor('${f.id}')">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhum fornecedor.</div>'}
window.editCliente=id=>{const c=state.clientes.find(x=>x.id===id);$('clienteId').value=c.id;$('clienteNome').value=c.nome||'';$('clienteWhatsapp').value=c.whatsapp||'';$('clienteEmail').value=c.email||'';$('clienteObs').value=c.obs||'';document.querySelector('[data-page="clientes"]').click()};
window.editFornecedor=id=>{const f=state.fornecedores.find(x=>x.id===id);$('fornecedorId').value=f.id;$('fornecedorNome').value=f.nome||'';$('fornecedorContato').value=f.contato||'';$('fornecedorCategoria').value=f.categoria||'';$('fornecedorObs').value=f.obs||'';document.querySelector('[data-page="fornecedores"]').click()};
window.delCliente=async id=>{if(confirm('Excluir cliente?')){await deleteDoc(doc(db,'clientes',id));refresh()}}; window.delFornecedor=async id=>{if(confirm('Excluir fornecedor?')){await deleteDoc(doc(db,'fornecedores',id));refresh()}};

function popularSelects(){$('clienteVenda').innerHTML='<option value="">Cliente não informado</option>'+state.clientes.map(c=>`<option value="${c.id}">${c.nome}</option>`).join('');$('compraFornecedor').innerHTML='<option value="">Fornecedor não informado</option>'+state.fornecedores.map(f=>`<option value="${f.id}">${f.nome}</option>`).join('');$('compraProduto').innerHTML='<option value="">Não atualizar estoque</option>'+state.produtos.map(p=>`<option value="${p.id}">${p.nome}</option>`).join('')}

// compras
$('compraForm').addEventListener('submit',async e=>{e.preventDefault();const produtoId=$('compraProduto').value,qtd=+$('compraQtd').value||0,valor=+$('compraValor').value||0;const compra={fornecedorId:$('compraFornecedor').value,produtoId,descricao:$('compraDescricao').value.trim(),quantidade:qtd,valor,data:$('compraData').value,obs:$('compraObs').value.trim(),criadoEm:new Date().toISOString(),timestamp:serverTimestamp()}; if(!compra.descricao||qtd<=0||valor<=0||!compra.data)return toast('Preencha a compra.'); await addDoc(collection(db,'compras'),compra); if(produtoId){const p=state.produtos.find(x=>x.id===produtoId);await updateDoc(doc(db,'produtos',produtoId),{estoque:(+p.estoque||0)+qtd,atualizadoEm:new Date().toISOString()})} e.target.reset();$('compraData').value=hoje();toast('Compra registrada');refresh()});
function renderCompras(){$('listaCompras').innerHTML=state.compras.length?state.compras.map(c=>{const f=state.fornecedores.find(x=>x.id===c.fornecedorId);return `<div class="info"><div><strong>${c.descricao}</strong><small>Fornecedor: ${f?.nome||'-'}</small><small>Qtd: ${c.quantidade} | Valor: ${fmt(c.valor)}</small><small>Data: ${c.data?dateBR.format(new Date(c.data+'T00:00:00')):'-'}</small><small>${c.obs||''}</small></div></div>`}).join(''):'<div class="empty">Nenhuma compra.</div>'}

// venda
function renderProdutosVenda(){const busca=($('buscaVenda').value||'').toLowerCase();const lista=state.produtos.filter(p=>p.ativo!==false&&[p.nome,p.sku,p.categoria].join(' ').toLowerCase().includes(busca));$('listaProdutosVenda').innerHTML=lista.length?lista.map(p=>`<button class="product" onclick="addVenda('${p.id}')"><strong>${p.nome}</strong><small>${p.categoria||'Sem categoria'} | Estoque: ${p.estoque||0}</small><span>${fmt(p.preco)}</span></button>`).join(''):'<div class="empty">Nenhum produto ativo.</div>'}
document.querySelectorAll('.pay').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pay').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.pagamento=b.dataset.pay}); $('descontoVenda').oninput=renderCarrinho; $('limparVenda').onclick=()=>{state.carrinho=[];$('descontoVenda').value=0;$('obsVenda').value='';renderCarrinho()};
window.addVenda=id=>{const p=state.produtos.find(x=>x.id===id);const item=state.carrinho.find(x=>x.id===id); if(item)item.qtd++; else state.carrinho.push({id:p.id,nome:p.nome,preco:+p.preco||0,custo:+p.custo||0,qtd:1}); renderCarrinho()};
window.qtdVenda=(id,d)=>{const i=state.carrinho.find(x=>x.id===id); if(!i)return; i.qtd+=d; if(i.qtd<=0)state.carrinho=state.carrinho.filter(x=>x.id!==id); renderCarrinho()};
function renderCarrinho(){const sub=state.carrinho.reduce((s,i)=>s+i.preco*i.qtd,0), desc=+$('descontoVenda').value||0,total=Math.max(0,sub-desc);$('totalVenda').textContent=fmt(total);$('carrinho').className=state.carrinho.length?'':'empty';$('carrinho').innerHTML=state.carrinho.length?state.carrinho.map(i=>`<div class="cart-item"><div><b>${i.nome}</b><br><small>${fmt(i.preco)} cada</small></div><button class="qty" onclick="qtdVenda('${i.id}',-1)">-</button><b>${i.qtd}</b><button class="qty" onclick="qtdVenda('${i.id}',1)">+</button><b>${fmt(i.preco*i.qtd)}</b></div>`).join(''):'Nenhum produto adicionado.'}
$('finalizarVenda').onclick=async()=>{if(!state.carrinho.length)return toast('Adicione produto.');const desc=+$('descontoVenda').value||0,sub=state.carrinho.reduce((s,i)=>s+i.preco*i.qtd,0),custo=state.carrinho.reduce((s,i)=>s+i.custo*i.qtd,0),total=Math.max(0,sub-desc),cliente=state.clientes.find(c=>c.id===$('clienteVenda').value);const venda={data:hoje(),mes:mes(),clienteId:cliente?.id||'',clienteNome:cliente?.nome||'',pagamento:state.pagamento,desconto:desc,subtotal:sub,total,custoTotal:custo,lucro:total-custo,obs:$('obsVenda').value.trim(),itens:state.carrinho.map(i=>({produtoId:i.id,nome:i.nome,preco:i.preco,custo:i.custo,quantidade:i.qtd,subtotal:i.preco*i.qtd,lucro:(i.preco-i.custo)*i.qtd})),criadoEm:new Date().toISOString(),timestamp:serverTimestamp()}; await addDoc(collection(db,'vendas'),venda); for(const i of state.carrinho){const p=state.produtos.find(x=>x.id===i.id);await updateDoc(doc(db,'produtos',i.id),{estoque:Math.max(0,(+p.estoque||0)-i.qtd),atualizadoEm:new Date().toISOString()})} state.carrinho=[];$('descontoVenda').value=0;$('obsVenda').value='';renderCarrinho();toast('Venda finalizada');refresh()};

// dashboard relatorio
function soma(a,c){return a.reduce((s,x)=>s+(+x[c]||0),0)}
function dashboard(){const h=hoje(),m=mes(),vh=state.vendas.filter(v=>v.data===h),vm=state.vendas.filter(v=>(v.data||'').startsWith(m)),cm=state.compras.filter(c=>(c.data||'').startsWith(m));const th=soma(vh,'total'),tm=soma(vm,'total'),saida=soma(cm,'valor'),lucro=soma(vm,'lucro')-saida;$('topHoje').textContent=$('dashHoje').textContent=fmt(th);$('dashEntradas').textContent=fmt(tm);$('dashSaidas').textContent=fmt(saida);$('dashLucro').textContent=fmt(lucro);charts(vm,tm,saida,lucro)}
function charts(vm,tm,saida,lucro){const dias=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);dias.push(d.toISOString().slice(0,10))}const vals=dias.map(d=>soma(state.vendas.filter(v=>v.data===d),'total')),labs=dias.map(d=>dateBR.format(new Date(d+'T00:00:00'))); if(chartDias)chartDias.destroy(); chartDias=new Chart($('graficoDias'),{type:'bar',data:{labels:labs,datasets:[{label:'Vendas',data:vals}]},options:{plugins:{legend:{display:false}}}}); const pags={'Dinheiro':0,'Pix':0,'Cartão de crédito':0,'Cartão de débito':0};vm.forEach(v=>pags[v.pagamento]=(pags[v.pagamento]||0)+(+v.total||0)); if(chartPag)chartPag.destroy(); chartPag=new Chart($('graficoPagamentos'),{type:'doughnut',data:{labels:Object.keys(pags),datasets:[{data:Object.values(pags)}]}}); if(chartResumo)chartResumo.destroy(); chartResumo=new Chart($('graficoResumo'),{type:'bar',data:{labels:['Entradas','Saídas','Saldo'],datasets:[{data:[tm,saida,lucro]}]},options:{plugins:{legend:{display:false}}}}); const rank={};vm.forEach(v=>(v.itens||[]).forEach(i=>rank[i.nome]=(rank[i.nome]||0)+(+i.quantidade||0)));const r=Object.entries(rank).sort((a,b)=>b[1]-a[1]).slice(0,7);$('ranking').innerHTML=r.length?r.map((x,i)=>`<div class="rank"><b>${i+1}. ${x[0]}</b><span>${x[1]} un.</span></div>`).join(''):'<div class="empty">Sem vendas no mês.</div>'}
$('gerarRelatorio').onclick=relatorio; $('exportarCSV').onclick=csv;
function periodo(arr){const ini=$('relInicio').value,fim=$('relFim').value;return arr.filter(x=>(!ini||x.data>=ini)&&(!fim||x.data<=fim))}
function relatorio(){const v=periodo(state.vendas),c=periodo(state.compras),ent=soma(v,'total'),sai=soma(c,'valor'),luc=soma(v,'lucro')-sai;$('relEntradas').textContent=fmt(ent);$('relSaidas').textContent=fmt(sai);$('relLucro').textContent=fmt(luc);$('relQtd').textContent=v.length;$('relTabela').innerHTML=v.length?v.map(x=>`<tr><td>${x.data?dateBR.format(new Date(x.data+'T00:00:00')):'-'}</td><td>${x.clienteNome||'-'}</td><td>${x.pagamento}</td><td>${(x.itens||[]).map(i=>i.quantidade+'x '+i.nome).join(', ')}</td><td>${fmt(x.total)}</td><td>${fmt(x.lucro)}</td></tr>`).join(''):'<tr><td colspan="6">Nenhuma venda.</td></tr>'}
function csv(){const v=periodo(state.vendas),rows=[['Data','Cliente','Pagamento','Itens','Subtotal','Desconto','Total','Custo','Lucro','Obs']];v.forEach(x=>rows.push([x.data,x.clienteNome,x.pagamento,(x.itens||[]).map(i=>i.quantidade+'x '+i.nome).join(' | '),x.subtotal,x.desconto,x.total,x.custoTotal,x.lucro,x.obs||'']));const text=rows.map(r=>r.map(c=>'"'+String(c??'').replaceAll('"','""')+'"').join(';')).join('\n');const blob=new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='relatorio-canecas-del-rei-'+hoje()+'.csv';a.click();URL.revokeObjectURL(url)}
